name: EasyTeX
services:
  frontend:
    build: "./frontend"
    container_name: frontend
    ports:
      - "3000:3000" 
    volumes:
     - ./frontend:/app
     - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_URL=http://localhost:8100
  backend:
    build: "./backend"
    container_name: backend
    ports:
      - "8100:8100" 
    volumes:
     - ./backend:/app
     - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_PORT=8100
      - MONGO_URL=mongodb://user:pass@mongodb/EasyTeX?authSource=admin
    privileged: true 
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: database
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./dbInit:/docker-entrypoint-initdb.d
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - "27000:27017"
volumes:
  frontend_node_modules:

    